from collections.abc import Iterable, Mapping
from typing import Any, Protocol, runtime_checkable

from comet.driver.generic import InstrumentError

from .resource import Resource

__all__ = [
    "InstrumentAdapter",
    "adapter_registry",
    "adapter_factory",
]


def handle_exception(method):
    def handle_exception(self, *args, **kwargs):
        try:
            return method(self, *args, **kwargs)
        except Exception as exc:
            raise AdapterError(f"{type(self).__name__}: {exc}") from exc

    return handle_exception


class AdapterError(Exception): ...


class InstrumentAdapter(Protocol):
    def __init__(self, resource: Resource) -> None: ...
    def identify(self) -> str: ...
    def reset(self) -> None: ...
    def clear(self) -> None: ...
    def next_error(self) -> InstrumentError | None: ...
    def configure(self, options: Mapping[str, Any]) -> None: ...


class SourceMeterAdapter(InstrumentAdapter, Protocol):
    def get_output_enabled(self) -> bool: ...
    def set_output_enabled(self, enabled: bool) -> None: ...
    def get_voltage_level(self) -> float: ...
    def set_voltage_level(self, level: float) -> None: ...
    def set_voltage_range(self, level: float) -> None: ...
    def set_current_compliance_level(self, level: float) -> None: ...
    def compliance_tripped(self) -> bool: ...
    def measure_i(self) -> float: ...
    def measure_iv(self) -> tuple[float, float]: ...


class ElectrometerAdapter(SourceMeterAdapter, Protocol):
    def set_zero_check_enabled(self, enabled: bool) -> None: ...


class LCRMeterAdapter(SourceMeterAdapter, Protocol):
    def measure_impedance(self) -> tuple[float, float]: ...


class DMMAdapter(InstrumentAdapter, Protocol):
    def measure_temperature(self) -> float: ...


class TCUAdapter(InstrumentAdapter, Protocol):
    def get_temperature(self) -> float: ...
    def get_humidity(self) -> float: ...
    def is_setpoint_enabled(self) -> bool: ...
    def set_setpoint_enabled(self, enabled: bool) -> None: ...
    def set_target_temperature(self, temperature: float) -> None: ...
    def is_within_setpoint(self) -> bool: ...
    def get_state(self) -> str: ...
    def handle_event(self, event: Any) -> None: ...


class SwitchingMatrixAdapter(InstrumentAdapter, Protocol):
    def close_channels(self, channels: Iterable[str]) -> None: ...
    def open_channels(self, channels: Iterable[str]) -> None: ...
    def open_all_channels(self) -> None: ...
    def closed_channels(self) -> list[str]: ...


@runtime_checkable
class VoltageMeasurable(Protocol):
    def measure_v(self) -> float: ...


adapter_registry: dict[str, type[InstrumentAdapter]] = {}


def adapter_factory(model: str) -> type[InstrumentAdapter]:
    """Return a instrument adapter class for a given model."""
    try:
        return adapter_registry[model]
    except KeyError as exc:
        raise ValueError(f"Unknown instrument model: {model}") from exc
