import logging
from typing import Any, Iterator, Optional, Protocol

from comet.driver.generic import InstrumentError

from ..resource import Resource

logger = logging.getLogger(__name__)

__all__ = ["Driver", "BaseDriver"]


def handle_exception(method):
    def handle_exception(self, *args, **kwargs):
        try:
            return method(self, *args, **kwargs)
        except Exception as exc:
            raise DriverError(f"{type(self).__name__}: {exc}") from exc

    return handle_exception


class DriverError(Exception): ...


class BaseDriver:
    def __init__(self, resource: Resource) -> None:
        self.resource = resource


class Driver(Protocol):
    def __init__(self, resource: Resource) -> None: ...
    def identify(self) -> str: ...
    def reset(self) -> None: ...
    def clear(self) -> None: ...
    def next_error(self) -> Optional[InstrumentError]: ...
    def configure(self, options: dict[str, Any]) -> None: ...


class SourceMeter(Driver, Protocol):
    def get_output_enabled(self) -> bool: ...
    def set_output_enabled(self, enabled: bool) -> None: ...
    def get_voltage_level(self) -> float: ...
    def set_voltage_level(self, level: float) -> None: ...
    def set_voltage_range(self, level: float) -> None: ...
    def set_current_compliance_level(self, level: float) -> None: ...
    def compliance_tripped(self) -> bool: ...
    def measure_i(self) -> float: ...
    def measure_iv(self) -> tuple[float, float]: ...


class Electrometer(SourceMeter, Protocol):
    def set_zero_check_enabled(self, enabled: bool) -> None: ...


class LCRMeter(SourceMeter, Protocol):
    def measure_impedance(self) -> tuple[float, float]: ...


class DMM(Driver, Protocol):
    def measure_temperature(self) -> float: ...


class TCU(Driver, Protocol):
    def get_temperature(self) -> float: ...
    def set_target_temperature(self, temperature: float) -> None: ...
    def is_within_setpoint(self) -> bool: ...
    def get_state(self) -> str: ...


class SwitchingMatrix(Driver, Protocol):
    def close_channels(self, channels: Iterator[str]) -> None: ...
    def open_channels(self, channels: Iterator[str]) -> None: ...
    def open_all_channels(self) -> None: ...
    def closed_channels(self) -> list[str]: ...
