from .core.measurement import MeasurementSpec

__all__ = ["MEASUREMENT_SPECS"]


MEASUREMENT_SPECS: list[MeasurementSpec] = [
    MeasurementSpec(
        id="iv",
        type="iv",
        title="IV",
        instruments=["smu", "elm", "elm2"],
        default_instruments=["smu"],
        default_begin_voltage=0.0,
        default_end_voltage=-300.0,
        default_step_voltage=5.0,
        default_waiting_time=0.5,
        default_current_compliance=10.0e-6,
        voltage_unit="V",
        current_compliance_unit="uA",
        is_continuous=True,
    ),
    MeasurementSpec(
        id="iv_bias",
        type="iv_bias",
        title="IV Bias",
        instruments=["smu", "smu2", "elm", "elm2"],
        default_instruments=["smu", "smu2"],
        default_begin_voltage=0.0,
        default_end_voltage=-300.0,
        default_step_voltage=5.0,
        default_waiting_time=0.5,
        default_bias_voltage=0.0,
        default_current_compliance=10.0e-6,
        voltage_unit="V",
        current_compliance_unit="uA",
        is_continuous=True,
    ),
    MeasurementSpec(
        id="cv_diode",
        type="cv",
        title="CV Diode",
        instruments=["smu", "lcr"],
        default_instruments=["smu", "lcr"],
        default_begin_voltage=0.0,
        default_end_voltage=50.0,
        default_step_voltage=1.0,
        default_waiting_time=0.3,
        default_current_compliance=100.0e-6,
        voltage_unit="V",
        current_compliance_unit="uA",
    ),
    MeasurementSpec(
        id="cv_mos",
        type="cv",
        title="CV MOS",
        instruments=["lcr"],
        default_instruments=["lcr"],
        default_begin_voltage=-10.0,
        default_end_voltage=10.0,
        default_step_voltage=1.0,
        default_waiting_time=1.0,
        default_current_compliance=10.0e-9,
        voltage_unit="V",
        current_compliance_unit="nA",
    ),
]
