from .core.measurement import MeasurementParameters
from .measurements import CVMeasurement, IVBiasMeasurement, IVMeasurement

__all__ = ["measurement_registry"]


measurement_registry: list[MeasurementParameters] = [
    MeasurementParameters(
        id="iv",
        type="iv",
        title="IV",
        measurement_cls=IVMeasurement,
        supported_roles=["smu", "elm", "elm2"],
        default_roles=["smu"],
        default_begin_voltage=0.0,
        default_end_voltage=-300.0,
        default_step_voltage=5.0,
        default_waiting_time=0.5,
        default_current_compliance=10.0e-6,
        voltage_unit="V",
        current_compliance_unit="uA",
        provides_continuous=True,
    ),
    MeasurementParameters(
        id="iv_bias",
        type="iv_bias",
        title="IV Bias",
        measurement_cls=IVBiasMeasurement,
        supported_roles=["smu", "smu2", "elm", "elm2"],
        default_roles=["smu", "smu2"],
        default_begin_voltage=0.0,
        default_end_voltage=-300.0,
        default_step_voltage=5.0,
        default_waiting_time=0.5,
        default_bias_voltage=0.0,
        default_current_compliance=10.0e-6,
        voltage_unit="V",
        current_compliance_unit="uA",
        provides_continuous=True,
    ),
    MeasurementParameters(
        id="cv_diode",
        type="cv",
        title="CV Diode",
        measurement_cls=CVMeasurement,
        supported_roles=["smu", "lcr"],
        default_roles=["smu", "lcr"],
        default_begin_voltage=0.0,
        default_end_voltage=50.0,
        default_step_voltage=1.0,
        default_waiting_time=0.3,
        default_current_compliance=100.0e-6,
        voltage_unit="V",
        current_compliance_unit="uA",
    ),
    MeasurementParameters(
        id="cv_mos",
        type="cv",
        title="CV MOS",
        measurement_cls=CVMeasurement,
        supported_roles=["lcr"],
        default_roles=["lcr"],
        default_begin_voltage=-10.0,
        default_end_voltage=10.0,
        default_step_voltage=1.0,
        default_waiting_time=1.0,
        default_current_compliance=10.0e-9,
        voltage_unit="V",
        current_compliance_unit="nA",
    ),
]
