# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Windows application

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '**' # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel flake8 pytest pyusb pyserial gpib-ctypes
        pip install pyinstaller==4.10.* pyinstaller-versionfile==2.0.*
        pip install .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Build with pyinstaller
      run: |
        pyinstaller pyinstaller.spec
    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        name: diode-measurement
        path: dist/diode-measurement*.exe
